---
- name: Join Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Check if node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_check

    - name: Fetch join command from master
      delegate_to: master1
      command: cat /tmp/join_command.txt
      register: join_command
      changed_when: false
      when: not kubelet_check.stat.exists

    - name: Join Kubernetes cluster
      command: "{{ join_command.stdout }}"
      when: not kubelet_check.stat.exists